### ISSUE TITLE
easencode.exe location or .py scripts installation instruction

### ISSUE THREAD

**Issue by abirger** [jmcmellen/sameeas#1]
@jmcmellen , I was looking for the EAS data generating software for a long time, and I ran into this repo. Unfortunately, the `easencode.exe` is not available, and my knowledge of Python is insufficient to install and use the scripts 'as-is'. Could you please provide me with the link to the `easencode.exe` module, or instruct how to install the scripts in the Miniconda environment? Thank you.

Sorry, never mind. Figured everything out. Thanks a lot for the software!

**Comment by SSP6904** [comment]
How did you do it?

**Comment by SavannahJohnston** [comment]
@SSP6904 

I don't know how to do it if you're on Windows, but if you're on Mac it works like this (quoting myself from another thread):

> If you're on Mac, to run a Python program you have to run it not by opening the file directly, but by using Terminal to go to the folder, then type "python [name of file] [command]". So, for instance, "python easencode.py -h". Don't know if this helps you (I don't know how it works on other OSes), but hopefully you can make yours work too. Best of luck.
